language: objective-c

osx_image: xcode8.3

install:
  - mkdir -p /Users/travis/build/reposandermets/.nvm
  - export NVM_DIR="/Users/travis/build/reposandermets/.nvm"
  - brew install nvm
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 8
  - npm i -g yarn jest
  - yarn

script:
  - jest
